### ISSUE TITLE
Complete the testcase

### ISSUE THREAD

**Issue by mhebing** [ddionrails/testsuite#11]
## Task overview

- [x] create good test data (incl. metadata with test definitions) --> TDP
- [x] setup file structure (see below) from raw data to statistics (including BMI generation and full statistics with weights and bi)
- [x] create limesurvesy questionnaire for p
- [x] Integrate more tests in ddi.py.

## Test data for the first run

- p dataset with
  - id
  - wave
  - body_weight
  - body_height
  - weight
- generate pgen with
  - id
  - bmi

## Update file structure

Create a directory for each project step. Within each directory use our normal directory layout.
Design: see #12

```
|-- 01-data-collection/
|   |-- output/        # place for the raw data
|-- 02-data-processing/
|   |-- import.*       # get data from data-collection
|   |-- input-test.*   # test raw data
|   |-- main.*         # run all processing scripts
|   |-- lib_py/
|   |-- input/ output/ etc.
|   |-- output-test.*
|-- 03-generate-statistics/
|   |-- get data from data-processing, generate statistics
|-- main.sh
```
